POST http://localhost:3333/planos HTTP/1.1
Content-Type: application/json
Authorization: beater eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjE0NTk1MjgyLCJleHAiOjE2MTUyMDAwODJ9.xpcmd84vNoxPUEOFNPlod3LnWtHU4cDFVAusXNS0SIo

{
  "title": "Carga Nice",
  "duration" : 6,
  "price" : 89
}

###
GET http://localhost:3333/planos HTTP/1.1
Content-Type: application/json
Authorization: beater eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjE0NTk1MjgyLCJleHAiOjE2MTUyMDAwODJ9.xpcmd84vNoxPUEOFNPlod3LnWtHU4cDFVAusXNS0SIo

###
PUT http://localhost:3333/planos/1 HTTP/1.1
Content-Type: application/json
Authorization: beater eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjE0NTk1MjgyLCJleHAiOjE2MTUyMDAwODJ9.xpcmd84vNoxPUEOFNPlod3LnWtHU4cDFVAusXNS0SIo

{
  "title" : "Start"
}

###

DELETE http://localhost:3333/planos/4 HTTP/1.1
Content-Type: application/json
Authorization: beater eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjE0NTk1MjgyLCJleHAiOjE2MTUyMDAwODJ9.xpcmd84vNoxPUEOFNPlod3LnWtHU4cDFVAusXNS0SIo
