POST http://localhost:3333/students HTTP/1.1
Content-Type: application/json
Authorization: beater eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjE0NTk1MjgyLCJleHAiOjE2MTUyMDAwODJ9.xpcmd84vNoxPUEOFNPlod3LnWtHU4cDFVAusXNS0SIo

{
  "name" : "Hamilton Silva",
  "email" : "hamilton@gmail.com",
  "idade" : 19,
  "peso" : 62.2,
  "altura" : 72.9
  }

###

GET http://localhost:3333/students HTTP/1.1
Authorization: beater eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjE0NTk1MjgyLCJleHAiOjE2MTUyMDAwODJ9.xpcmd84vNoxPUEOFNPlod3LnWtHU4cDFVAusXNS0SIo
